### ISSUE TITLE
Solution in Presolved Reduced Space

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#36]
If I have a solution (or partial solution) to the original problem defined in a .sol file, is there a way to construct the corresponding solution (or partial solution) in the presolved reduced space?

This might be useful if a good solution (or partial solution) to the original problem is known (for example from a metaheuristic) and I want to provide this initial feasible solution (or partial solution) and the presolved reduced problem to the solver (e.g., Gurobi).

**Comment by alexhoen** [comment]
in general, there is no easy way to provide such a solution.

Dual presolvers (DualFix/DualInfer) or presolvers based on symmetry arguments (parallelcols/DomCol) cut off feasible e (even optimal as long one optimal remains in the problem) solutions. 

1. disable all dual presolvers via parameter, then take variables present in the presolved problem
2. drop all variables from the original solution and check if they have the same value in postsolve stack. In case they are conflicting with the presolved problem, some variables may need to be reshifted in order to fulfill all constraints.
