### ISSUE TITLE
Misleading prints in interface

### ISSUE THREAD

**Issue by rolfvdhulst** [scipopt/papilo#57]
Setting verbosity to 3 (e.g. normal level), Papilo's command line output seems to suggest e.g. the following;

round 2 is FAST 
round 3 is EXHAUSTIVE

e.g. that it did not perform a search for MEDIUM; however, in fact, it did another FAST and MEDIUM round in between, which both did not find any reductions. Only the rounds where reductions are found are printed, which can be quite misleading, as there are therefore much more rounds being done than there are being printed.

**Comment by alexhoen** [comment]
How the rounds in papilo work is described in Section 2.1 in the PaPILO paper: https://arxiv.org/abs/2206.10709

To summarize : 
- if a round of fast/medium/exhaustive presolver were "successful" the fast presolver is executed again
- if a round of fast presolver is not successful papilo calls the medium presolvers
- if a round of medium presolver is not successful papilo calls the exhaustive presolvers

So when you see this:
```
round 2 is FAST
round 3 is EXHAUSTIVE
```
you implicitly know that 1 round of fast presolver was successful, and 1 round of fast and medium presolver was unsuccessful. These unsuccessful runs can accumulate so that printing each would lead to a noisy log.  Since missing round numbers would also confuse users only successful rounds are counted.

Nevertheless, the number of calls of a presolver can be seen in the statistics and is probably more important than the rounds. 

Hope that helps
